# Configure max HEAP size
USER_FLAGS+="-Wl,--defsym,__cellrv32_heap_size=1024"

# Modify this variable to fit your CELLRV32 setup (cellrv32 home folder)
CELLRV32_HOME ?= ../../..

include $(CELLRV32_HOME)/sw/common/common.mk
