# Modify this variable to fit your CELLRV32 setup (cellrv32 home folder)
CELLRV32_HOME ?= ../../..

APP_SRC ?= $(wildcard ./*.c) $(wildcard ./*.s) $(wildcard ./*.cpp) $(wildcard ./*.S) $(wildcard ./drv/*.c)
APP_INC ?= -I . -I ./drv

include $(CELLRV32_HOME)/sw/common/common.mk
